Creating a 2D Matrix (Height × Width)

In [17]:
import numpy as np

matrix_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix_2d.shape)
print(matrix_2d)

print(matrix_2d.size)

print(matrix_2d[:,0]) # Select Left Column Matrix
print(matrix_2d[1,:]) # Select Middle ROw
print(matrix_2d[0:2,0:2])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[1 4 7]
[4 5 6]
[[1 2]
 [4 5]]


Creating 3D matrix ( 2 layers of 3x3)

In [11]:
matrix_3d=np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],

    [[10,11,12],
     [13,14,15],
     [16,17,18]]
])

print(matrix_3d.shape)
print(matrix_3d)
print(matrix_3d.size)

(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
18


Creating an nD Matrix (4D)

In [29]:
matrix_4d=np.random.rand(2,3,3,3)

print(matrix_4d.shape)

#print(matrix_4d)

matrix_4d_z=np.zeros((2,3,3,3))

print(matrix_4d_z.shape)

print(matrix_4d_z)

(2, 3, 3, 3)
(2, 3, 3, 3)
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


2D Tensor Using PyTorch

In [5]:
import torch

tensor_2d=torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(tensor_2d.shape)
print(tensor_2d)


torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


3D Tensor using PyTorch

In [6]:
tensor_3D =  torch.tensor([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(tensor_3D.shape)
print(tensor_3D)

torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


2D Tensor using Tensor Flow

In [20]:
import tensorflow as tf

tensor_2d=tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])

print(tensor_2d.shape)
print(tensor_2d)
tf.rank(tensor_2d)

tensor_2d_ALt=tf.Variable([
    [1,2,3,4],
    [5,6,7,8]
])

print(tensor_2d_ALt.shape)
print(tensor_2d_ALt)
tf.shape(tensor_2d_ALt)

(2, 4)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
(2, 4)
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

3D  Tensor using Tensor FLow

In [2]:
tensor_3d=tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(tensor_3d.shape)
print(tensor_3d)

(2, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


5D Tensor in TensorFlow

In [27]:
tensor_5d=tf.random.uniform((2,5,64,64,3))
print(tensor_5d.shape)
#print(tensor_5d)

tensor_5d_z=tf.zeros((2,5,64,64,3))
print(tensor_5d_z.shape)
#print(tensor_5d_z)

(2, 5, 64, 64, 3)
(2, 5, 64, 64, 3)


5D Tensor in Pytorch

In [22]:
import torch

tensor_5D = torch.rand(2,5,64,64,3)

print(tensor_5D.shape)


tensor_4d= torch.zeros([32,28,38,3])
print(tensor_4d.shape)
#print(tensor_4d)


torch.Size([2, 5, 64, 64, 3])
torch.Size([32, 28, 38, 3])
