**Tensor Operations**

In [2]:
import numpy as np
A=np.array([[1,2],[3,4]])
k=2

print(A+k)

print(A-k)

print(A*k)

print(A/k)

print(np.linalg.matrix_power(A,k))

[[3 4]
 [5 6]]
[[-1  0]
 [ 1  2]]
[[2 4]
 [6 8]]
[[0.5 1. ]
 [1.5 2. ]]
[[ 7 10]
 [15 22]]


Tensor Flow

In [3]:
import tensorflow as tf

A=tf.constant([[1,2],[3,4]], dtype=tf.float32)
k=2

print(A+k)

print(A-k)

print(A*k)

print(A/k)

print(tf.linalg.matmul(A,A))


tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.  0.]
 [ 1.  2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)


PyTorch

In [5]:
import torch

A=torch.tensor([[1,2],[3,4]], dtype=torch.float32)
k=torch.tensor(2.0)
print(A+k)

print(A-k)

print(A*k)

print(A/k)

print(torch.matrix_power(A, int(k)))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
tensor([[ 7., 10.],
        [15., 22.]])


Matrix Vs Matrix Operations

NumPy Implementation

In [7]:
import numpy as np

A = np.array([[2,3],[1,4]])
B = np.array([[5,6],[7,8]])

#addition

print(A+B)

#Substraction

print(A-B)

#Dot Product(Matrix Multiplication)

print(np.dot(A,B))

# Hadmard product

print(A*B)

#Elementwise division

print(A/B)

# Division using Inverse
B_inv=np.linalg.inv(B)
print(np.dot(A,B_inv))

[[ 7  9]
 [ 8 12]]
[[-3 -3]
 [-6 -4]]
[[31 36]
 [33 38]]
[[10 18]
 [ 7 32]]
[[0.4        0.5       ]
 [0.14285714 0.5       ]]
[[ 2.5 -1.5]
 [10.  -7. ]]


Using Pytorch

In [8]:
import torch

A=torch.tensor([[2,3],[1,4]], dtype=torch.float32)
B=torch.tensor([[5,6],[7,8]], dtype=torch.float32)

#addition

print(A+B)

#Substraction

print(A-B)

#dotProduct

print(torch.mm(A,B))

#Hadamard_Product

print(A*B)

#Element wise division

print(A/B)

#Division  using inverse
B_inv=torch.inverse(B)
print(torch.mm(A,B_inv))


tensor([[ 7.,  9.],
        [ 8., 12.]])
tensor([[-3., -3.],
        [-6., -4.]])
tensor([[31., 36.],
        [33., 38.]])
tensor([[10., 18.],
        [ 7., 32.]])
tensor([[0.4000, 0.5000],
        [0.1429, 0.5000]])
tensor([[ 2.5000, -1.5000],
        [10.0000, -7.0000]])


Using Tensor Flow

In [11]:
import tensorflow as tf

A=tf.constant([[2,3],[1,4]], dtype=tf.float32)
B=tf.constant([[5,6],[7,8]], dtype=tf.float32)

#addition
print( tf.add(A,B))

#substraction
print(tf.subtract(A,B))


#Dot product
print(tf.linalg.matmul(A,B))

#Hadmard Product
print(tf.multiply(A,B))

#Element wise divide
print(tf.divide(A,B))

#Division using Inverse
B_inv=tf.linalg.inv(B)
print(tf.linalg.matmul(A,B_inv))

tf.Tensor(
[[ 7.  9.]
 [ 8. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-3. -3.]
 [-6. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[31. 36.]
 [33. 38.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[10. 18.]
 [ 7. 32.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.4        0.5       ]
 [0.14285715 0.5       ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.500001  -1.500001 ]
 [10.000005  -7.0000033]], shape=(2, 2), dtype=float32)


Matrix determinant and adjugate (adjoint)

In [21]:
import numpy as np

# Define matrix A
A = np.array([[2, 3, 1], [4, 5, 6], [7, 8, 9]], dtype=np.float64)


det_A = np.linalg.det(A)
print("det_A\n", det_A)

A_inv = np.linalg.inv(A)
print("A_inv:\n", A_inv)


cofactor_A = (A_inv * det_A).T  # Transpose of adjugate matrix
print("cofactor_A:\n", cofactor_A)

adj_A = cofactor_A.T
print("\nAdjugate Matrix (Adj(A)):\n", adj_A)


det_A
 9.000000000000005
A_inv:
 [[-0.33333333 -2.11111111  1.44444444]
 [ 0.66666667  1.22222222 -0.88888889]
 [-0.33333333  0.55555556 -0.22222222]]
cofactor_A:
 [[ -3.   6.  -3.]
 [-19.  11.   5.]
 [ 13.  -8.  -2.]]

Adjugate Matrix (Adj(A)):
 [[ -3. -19.  13.]
 [  6.  11.  -8.]
 [ -3.   5.  -2.]]


Using Pytorch

In [22]:
import torch

A=torch.tensor([[2,3,1],[4,5,6],[7,8,9]], dtype=torch.float32)

det_A=torch.det(A)
A_inv=torch.inverse(A)
cofactor_A=(A_inv * det_A).T
adj_A=cofactor_A.T

print("det_A\n", det_A)
print("A_inv\n", A_inv)
print("cofactor_A\n", cofactor_A)
print("adj_A\n", adj_A)

det_A
 tensor(9.)
A_inv
 tensor([[-0.3333, -2.1111,  1.4444],
        [ 0.6667,  1.2222, -0.8889],
        [-0.3333,  0.5556, -0.2222]])
cofactor_A
 tensor([[ -3.0000,   6.0000,  -3.0000],
        [-19.0000,  11.0000,   5.0000],
        [ 13.0000,  -8.0000,  -2.0000]])
adj_A
 tensor([[ -3.0000, -19.0000,  13.0000],
        [  6.0000,  11.0000,  -8.0000],
        [ -3.0000,   5.0000,  -2.0000]])


Using Tensor Flow

In [23]:
import tensorflow as tf

A = tf.Variable([[2,3,1],[4,5,6],[7,8,9]], dtype=tf.float32)

det_A=tf.linalg.det(A)
A_inv=tf.linalg.inv(A)
cofactor_a=tf.transpose(A_inv * det_A)
adj_A=tf.transpose(cofactor_A)

print("det_A\n", det_A)
print("A_inv\n", A_inv)
print("cofactor_A\n", cofactor_A)
print("adj_A\n", adj_A)



det_A
 tf.Tensor(8.999996, shape=(), dtype=float32)
A_inv
 tf.Tensor(
[[-0.3333333  -2.1111124   1.4444451 ]
 [ 0.6666666   1.222223   -0.8888894 ]
 [-0.33333334  0.55555576 -0.22222236]], shape=(3, 3), dtype=float32)
cofactor_A
 tensor([[ -3.0000,   6.0000,  -3.0000],
        [-19.0000,  11.0000,   5.0000],
        [ 13.0000,  -8.0000,  -2.0000]])
adj_A
 tf.Tensor(
[[ -3.000002  -18.999998   13.       ]
 [  6.000002   10.999999   -8.       ]
 [ -2.9999998   4.999999   -1.9999996]], shape=(3, 3), dtype=float32)


In [24]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(A))        # Sum of all elements
print(np.sum(A, axis=0)) # Column-wise sum
print(np.sum(A, axis=1)) # Row-wise sum


21
[5 7 9]
[ 6 15]
